-- Drop table to reset definition (Safe since it is a new feature)
DROP TABLE IF EXISTS app_status;

-- Create table with GENERATED BY DEFAULT to allow manual ID insertion if needed
CREATE TABLE app_status (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    is_shutdown BOOLEAN DEFAULT FALSE,
    shutdown_stage INTEGER DEFAULT 0, -- 0: Normal, 1: Warning 1, 2: Warning 2, 3: Shutdown
    shutdown_time TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert the singleton row with ID=1
INSERT INTO app_status (id, is_shutdown, shutdown_stage)
VALUES (1, FALSE, 0);

-- Enable RLS
ALTER TABLE app_status ENABLE ROW LEVEL SECURITY;

-- Allow read access to everyone
CREATE POLICY "Allow public read access" ON app_status FOR SELECT USING (true);

-- Allow update access only to authenticated users
CREATE POLICY "Allow authenticated update" ON app_status FOR UPDATE USING (auth.role() = 'authenticated');
